/* ============================================================
   MODAL CONTENT — edit freely.
   Each key matches a data-modal="key" attribute in the HTML.
   Sections: { h: heading, p: [paragraphs], li: [bullets] }
   ============================================================ */
window.MODAL_DATA = {

  /* ---------------- PROJECTS ---------------- */

  'project-llm': {
    kicker: 'Research — NYU Osiris Lab',
    title: 'LLM Package Hallucination Detection System',
    sub: 'AI Security · LLM Supply Chain · Python',
    sections: [
      {
        p: ['A research-driven proof of concept that identifies and analyzes hallucinated or malicious package dependencies in code generated by large language models. The goal is to strengthen software supply chain security by validating imported libraries against verified sources, benchmarking hallucination behavior across <strong>GPT-4, Gemini, and Cohere</strong>.']
      },
      {
        h: 'System components',
        li: [
          '<strong>Chrome extension</strong> — integrates directly with online LLM interfaces, flagging suspicious package references in generated code in real time.',
          '<strong>Curated corpus</strong> — a collection of LLM-generated Python samples containing outdated or hallucinated dependencies, used to evaluate detection accuracy and improve robustness.',
          '<strong>Detection engine</strong> — a Python-based proof of concept that parses and validates imports in AI-generated code, catching hallucinated, outdated, or potentially harmful packages (including requirements.txt scanning).'
        ]
      },
      {
        h: 'Why it matters',
        p: ['When an LLM suggests a package that doesn\u2019t exist, an attacker can register that name and turn a hallucination into a working supply chain attack. This system closes that gap before the code is ever run.']
      },
      {
        h: 'Future work',
        li: [
          'Additional markers to better judge whether a package is malicious.',
          'Extending language support beyond Python.'
        ]
      }
    ],
    tags: ['AI Security', 'LLM Research', 'Supply Chain', 'Chrome Extension', 'Python'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/llm-package-hallucination/' },
      { label: 'GitHub', href: 'https://github.com/AlvinManojAlex/LLM-Package-Hallucination' }
    ]
  },

  'project-swiper': {
    kicker: 'Security — Data Protection',
    title: 'Swiper No Swiping',
    sub: 'PII Detection · Privacy · Chrome Extension',
    sections: [
      {
        p: ['A Chrome extension that identifies <strong>Personally Identifiable Information (PII)</strong> in sensitive documents before they\u2019re uploaded to the web \u2014 preventing accidental exposure of confidential data and supporting compliance with privacy regulations like <strong>GDPR</strong> and <strong>CCPA</strong>.']
      },
      {
        h: 'Key features',
        li: [
          '<strong>Real-time PII detection</strong> — automatically parses uploaded documents to flag names, emails, phone numbers, SSNs, and financial information for review and redaction.',
          '<strong>User-friendly UI</strong> — a simple, clean interface for seamless file scanning.',
          '<strong>Local processing</strong> — everything runs inside the browser; no files are transmitted externally, so privacy is preserved end to end.'
        ]
      },
      {
        h: 'Future work',
        li: [
          'Broader detection across financial, health, and location data in more file formats.',
          'Automated redaction and proactive real-time alerts during uploads and form submissions.',
          'NLP/ML integration to improve accuracy and reduce false positives.'
        ]
      }
    ],
    tags: ['Security', 'PII Detection', 'Privacy', 'GDPR / CCPA', 'Chrome Extension'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/swiper-no-swiping/' },
      { label: 'GitHub', href: 'https://github.com/AlvinManojAlex/Swiper-No-Swiping' }
    ]
  },

  'project-neuraflix': {
    kicker: 'Machine Learning',
    title: 'Neuraflix — Movie Recommendation System',
    sub: 'TMDB 5000 Dataset · Hybrid Recommenders · Python',
    sections: [
      {
        p: ['A data-driven recommendation system built on the <strong>TMDB 5000 Movie Dataset</strong>, comparing multiple recommendation paradigms \u2014 demographic, content-based, collaborative, and deep-learning hybrid models \u2014 with performance evaluated on industry-standard metrics.']
      },
      {
        h: 'Methodology',
        li: [
          '<strong>Demographic filtering</strong> — trending, high-rated titles from popularity scores and vote averages.',
          '<strong>Content-based filtering</strong> — TF-IDF vectorization + cosine similarity on movie overviews, enhanced with Truncated SVD.',
          '<strong>KNN filtering</strong> — CountVectorizer + Nearest Neighbors on textual features.',
          '<strong>Autoencoders</strong> — latent user\u2013movie representations for non-linear recommendations.',
          '<strong>Collaborative filtering</strong> — matrix factorization via SVD on a simulated rating matrix.'
        ]
      },
      {
        h: 'Results',
        p: ['Evaluated on 50 simulated users: Precision@10 0.058, NDCG@10 1.000, Accuracy 0.80, with low RMSE/MAE. Hybrid and autoencoder-based methods outperformed single-model approaches in balancing relevance and novelty.']
      }
    ],
    tags: ['Machine Learning', 'Recommenders', 'Deep Learning', 'Python', 'Data Science'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/neuraflix-movie-recommendation-system/' },
      { label: 'GitHub', href: 'https://github.com/Shrey12202/NeuralFlix-Movie-Recommendation-System-' }
    ]
  },

  'project-face-auth': {
    kicker: 'Authentication',
    title: 'Web Authentication via Face Recognition',
    sub: 'Flask · OpenCV · SQLAlchemy',
    sections: [
      {
        p: ['A web-based biometric login system (WAFR) built with <strong>Python, Flask, and OpenCV</strong> to explore face recognition as a stronger alternative to passwords, which are increasingly vulnerable to hacking and impersonation.']
      },
      {
        h: 'How it works',
        li: [
          'A front-end login view captures the user\u2019s face and sends the image to a recognition API.',
          'The API reconstructs the image and passes it to the classification model, which matches against the registered user\u2019s stored image.',
          'On registration, a unique code is <strong>encrypted and saved</strong> in the database; users can opt into face login alongside password auth \u2014 similar to two-factor enrollment.',
          'A match verifies the user and grants access; otherwise authentication fails.'
        ]
      },
      {
        h: 'Objectives',
        li: [
          'Web interface for capturing facial images.',
          'Efficient facial recognition for identity verification.',
          'Integration with standard web authentication mechanisms.',
          'Security features: encryption, access controls, and secure data storage.'
        ]
      }
    ],
    tags: ['Authentication', 'Computer Vision', 'Biometrics', 'Flask', 'OpenCV', 'Web Security'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/web-authentication-face-recognition/' },
      { label: 'Documentation (PDF)', href: 'https://wp.nyu.edu/hemraj_patel/files/2025/01/Report.pdf' }
    ]
  },

  'project-malware-lab': {
    kicker: 'Threat Research',
    title: 'Malware Analysis Lab',
    sub: 'Offensive + Defensive Training Environment',
    sections: [
      {
        p: ['A controlled cybersecurity environment for comprehensive offensive and defensive training, structured around the <strong>WAFR (Weaponized Attack and Forensic Response)</strong> framework \u2014 covering the full arc from reconnaissance to incident response.']
      },
      {
        h: 'Phases & tooling',
        li: [
          '<strong>Reconnaissance</strong> — Nmap, Shodan, Recon-ng; identified 80%+ of open ports and services on target machines.',
          '<strong>Exploitation</strong> — Metasploit + MSFVenom; deployed known exploits (e.g. EternalBlue) with ~90% success on vulnerable targets.',
          '<strong>Privilege escalation</strong> — Mimikatz and Linux Exploit Suggester; root/admin access in ~75% of test cases.',
          '<strong>Detection & forensics</strong> — Wireshark and Volatility; classified custom malware samples at ~95% accuracy via static + dynamic analysis.',
          '<strong>Incident response</strong> — ELK Stack, Splunk, and Autopsy; contained a simulated ransomware attack within 30 seconds and restored ~98% of affected files.'
        ]
      },
      {
        h: 'Outcome',
        p: ['Results exceeded expected outcomes in every phase, providing a robust, hands-on foundation for understanding adversarial tactics and building cyber resilience.']
      }
    ],
    tags: ['Malware Analysis', 'Threat Research', 'Sandboxing', 'Forensics', 'Metasploit', 'Splunk'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/malware-analysis-lab/' }
    ]
  },

  'project-sams': {
    kicker: 'Automation',
    title: 'Smart Attendance Management System',
    sub: 'Face Detection · MATLAB · Automation',
    sections: [
      {
        p: ['SAMS automates daily student attendance in schools and colleges using face detection: a capture device at the classroom door records every student\u2019s face as they enter, and attendance is uploaded before the lecture ends \u2014 no manual roll call.']
      },
      {
        h: 'Technical approach',
        li: [
          '<strong>Face detection</strong> — Viola-Jones algorithm.',
          '<strong>Recognition features</strong> — Histogram of Oriented Gradients (HOG).',
          '<strong>Classification</strong> — Error Correcting Output Coding (ECOC) with an SVM binary classifier.',
          '<strong>Platform</strong> — MATLAB for image processing and database management.'
        ]
      },
      {
        h: 'Results',
        li: [
          'Fully automated attendance marking with no manual input.',
          'Attendance reports and defaulter lists generated automatically.',
          'Faculty can verify and edit records when needed.'
        ]
      }
    ],
    tags: ['Automation', 'MATLAB', 'Computer Vision', 'SVM', 'Full Stack'],
    links: [
      { label: 'Project write-up', href: 'https://wp.nyu.edu/hemraj_patel/projects/smart-attendance-management-system/' },
      { label: 'Documentation (PPTX)', href: 'https://wp.nyu.edu/hemraj_patel/files/2025/01/SAMS.pptx' }
    ]
  },

  'research-focus': {
    kicker: 'Research — NYU Osiris Lab',
    title: 'Adversarial ML & LLM Supply Chain Security',
    sub: 'Current research focus',
    sections: [
      {
        p: ['My work at the NYU Osiris Lab explores how adversarial techniques can compromise machine learning models, with particular emphasis on <strong>LLM supply chain vulnerabilities</strong>, data integrity, and model poisoning.'],
      },
      {
        p: ['The Package Hallucination Detection System is the foundational tool of this research: it identifies when LLMs suggest non-existent dependencies \u2014 a vector that becomes a real supply chain attack the moment a malicious actor registers a hallucinated package name.']
      }
    ],
    tags: ['Adversarial ML', 'LLM Security', 'Supply Chain', 'Data Integrity', 'Model Poisoning'],
    links: [
      { label: 'LLM Hallucination project', href: 'https://wp.nyu.edu/hemraj_patel/projects/llm-package-hallucination/' }
    ]
  },

  /* ---------------- EXPERIENCE ---------------- */

  'exp-nyu-research': {
    kicker: 'Experience',
    title: 'Student Research Assistant — New York University',
    sub: 'Sep 2024 — May 2026 · Part-time · New York, NY',
    sections: [
      {
        li: [
          'Researching AI-driven cyber threats and adversarial machine learning models at the NYU Osiris Lab.',
          'Focus areas: data integrity, model poisoning, and system trustworthiness in cloud and emerging AI systems.',
          'Building the Package Hallucination Detection System, benchmarking hallucination rates across GPT-4, Gemini, and Cohere.',
          'Working in Python and TensorFlow across LLM supply chain security experiments.'
        ]
      }
    ],
    tags: ['AI Threat Research', 'Adversarial ML', 'LLM Security', 'Python', 'TensorFlow']
  },

  'exp-nyu-admin': {
    kicker: 'Experience',
    title: 'Graduate Administrative Assistant — New York University',
    sub: 'May 2025 — Sep 2025 · Full-time · New York, NY',
    sections: [
      {
        li: [
          'Managed Microsoft server administration and user account access for the NYU Economics Department.',
          'Handled system troubleshooting, Active Directory, Group Policy, and Azure AD administration.',
          'Maintained CMS/WordPress websites and secure faculty webpages.'
        ]
      }
    ],
    tags: ['Microsoft Servers', 'Active Directory', 'Azure AD', 'Access Control', 'WordPress']
  },

  'exp-span': {
    kicker: 'Experience',
    title: 'Security Engineer — SPAN Inspection Systems Pvt. Ltd.',
    sub: 'May 2023 — Jul 2024 · Full-time · Gandhinagar, GJ, India',
    sections: [
      {
        li: [
          'Deployed and managed <strong>Nessus and OpenVAS across 300+ endpoints</strong>.',
          'Remediated <strong>500+ vulnerabilities</strong>, contributing to a <strong>40% reduction in high-severity risks</strong>.',
          'Built Python-based automation for patch management and CVE ingestion.',
          'Integrated scan results into Splunk dashboards and MITRE ATT&CK-aligned workflows.'
        ]
      }
    ],
    tags: ['Nessus', 'OpenVAS', 'Python', 'Splunk', 'MITRE ATT&CK', 'Patch Management', 'Linux']
  },

  'exp-techdefence': {
    kicker: 'Experience',
    title: 'Security Analyst — TechDefence',
    sub: 'May 2022 — Apr 2023 · Internship · Ahmedabad, GJ, India',
    sections: [
      {
        li: [
          'Conducted vulnerability assessments and penetration tests using Burp Suite, Metasploit, and OWASP ZAP.',
          'Identified and helped remediate <strong>100+ application vulnerabilities</strong>.',
          'Monitored SIEM alerts in Splunk and ELK and automated alert correlation.',
          'Reduced false positives by <strong>28%</strong>.'
        ]
      }
    ],
    tags: ['Burp Suite', 'Metasploit', 'OWASP ZAP', 'Splunk', 'ELK', 'SIEM', 'Pentesting']
  },

  /* ---------------- ATHLETICS ---------------- */

  'athletics-journey': {
    kicker: 'Athletics — From Pool to Protocol',
    gold: true,
    title: 'My Journey as an Athlete',
    sub: '200+ state medals · National medalist · 15 years of competition',
    sections: [
      {
        p: [
          'My sports journey began with skating, but in 2008 I discovered my true passion — swimming. The transition was life-changing, and by 2010 I was competing at the state level.',
          'Over the next decade, I earned <strong>200+ state medals and multiple national medals</strong>, representing my region at the highest levels of competition. Swimming taught me that excellence is not a single moment but a daily commitment.',
          'After a 1.5-year pause during COVID-19, I returned to intense training with even greater determination — swimming up to <strong>7.5 miles / 12 km per day</strong> with strength and conditioning work — and won my last national medal in 2023 before shifting focus to academics and cybersecurity.'
        ]
      },
      {
        h: 'Competition timeline',
        li: [
          '<strong>2008</strong> — Discovered swimming after starting out in skating.',
          '<strong>2010</strong> — First state-level competition, the start of a decade-long journey.',
          '<strong>2016</strong> — First national medal, validating years of intense training.',
          '<strong>2019</strong> — Continued national success while balancing academics.',
          '<strong>2020–2021</strong> — The COVID pause: 1.5 years away from competition.',
          '<strong>2023</strong> — Returned stronger than ever and won a final national medal before turning to cybersecurity.'
        ]
      },
      {
        h: 'The athlete mindset in cybersecurity',
        li: [
          '<strong>Discipline</strong> — 5 AM training and patch management both reward showing up every day; neither allows shortcuts.',
          '<strong>Pressure management</strong> — the final 50 meters of a race and the final hours of an incident response share the same adrenaline.',
          '<strong>Continuous improvement</strong> — a swimmer analyzes every stroke; a security engineer analyzes every alert.',
          '<strong>Team reliance</strong> — relay teams trust each other completely; security teams need the same clear handoffs.',
          '<strong>Adaptability</strong> — conditions change in the pool and in the threat landscape; adapting is survival.',
          '<strong>The long game</strong> — championships are won in training, and security posture is built in daily practice, not during breaches.'
        ]
      }
    ],
    tags: ['Swimming', 'Discipline', 'Resilience', 'Competitive Mindset'],
    links: [
      { label: 'Read the full story', href: 'https://wp.nyu.edu/hemraj_patel/my-journey-as-an-athlete/' }
    ]
  },

  /* ---------------- CERTIFICATIONS ---------------- */

  'cert-mastercard': {
    kicker: 'Certification',
    title: 'Cybersecurity Job Simulation',
    sub: 'Mastercard / Forage · Apr 2026',
    sections: [{ p: ['Stepped into the role of a security analyst on Mastercard\u2019s Security Awareness Team \u2014 identifying phishing threats and designing security awareness training for internal teams.'] }],
    tags: ['Phishing Analysis', 'Security Awareness'],
    links: [{ label: 'Related blog post', href: 'https://wp.nyu.edu/hemraj_patel/security-training-phishing-awareness/' }]
  },

  'cert-leetcode': {
    kicker: 'Certification',
    title: 'Career Hub LeetCode Bootcamp',
    sub: 'NYU Tandon School of Engineering · Jan 2026',
    sections: [{ p: ['Intensive problem-solving bootcamp covering data structures, algorithms, and technical interview preparation.'] }],
    tags: ['Algorithms', 'Data Structures', 'Interview Prep']
  },

  'cert-security-plus': {
    kicker: 'Certification',
    title: 'CompTIA Security+',
    sub: 'CompTIA · Aug 2025',
    sections: [{ p: ['Industry-standard certification validating baseline skills in threats and vulnerabilities, architecture and design, implementation, operations and incident response, and governance/risk/compliance.', 'Credential ID: <strong>D3VZNL3Y7NV4CW9J</strong> — verifiable through CompTIA’s official verification portal.'] }],
    tags: ['Security Fundamentals', 'Risk Management', 'Incident Response'],
    links: [{ label: 'Verify credential', href: 'https://www.certmetrics.com/comptia/public/verification.aspx/' }]
  },

  'cert-google': {
    kicker: 'Certification',
    title: 'Google Cybersecurity Certificate',
    sub: 'Google · May 2025',
    sections: [{ p: ['Hands-on program covering security frameworks, network security, Linux and SQL, detection and response, and Python automation for security tasks.'] }],
    tags: ['SIEM', 'Linux', 'SQL', 'Python'],
    links: [{ label: 'View credential', href: 'https://www.coursera.org/account/accomplishments/professional-cert/certificate/NQVL2QW4MQJV' }]
  },

  'cert-datascience': {
    kicker: 'Certification',
    title: 'Data Science Bootcamp Badge',
    sub: 'NYU Tandon School of Engineering · May 2025',
    sections: [{ p: ['Applied data science fundamentals: data wrangling, analysis, visualization, and introductory machine learning.'] }],
    tags: ['Data Science', 'Python', 'ML Basics'],
    links: [{ label: 'View credential', href: 'https://credentials.engineering.nyu.edu/3bb23272-77c2-479e-b06d-dc41fd6961db#acc.kTCaQPqc' }]
  },

  'cert-cissp': {
    kicker: 'Certification',
    title: 'CISSP — Candidate',
    sub: 'ISC2 · In progress',
    sections: [{ p: ['Preparing for the Certified Information Systems Security Professional certification — the gold-standard credential covering security and risk management, asset security, security architecture, network security, IAM, testing, operations, and software development security.'] }],
    tags: ['Security Architecture', 'Risk Management', 'Governance']
  },

  'cert-ccsk': {
    kicker: 'Certification',
    title: 'CCSK — Candidate',
    sub: 'Cloud Security Alliance · In progress',
    sections: [{ p: ['Preparing for the Certificate of Cloud Security Knowledge — vendor-neutral cloud security covering architecture, governance, compliance, data security, and cloud-native security operations.'] }],
    tags: ['Cloud Security', 'Governance', 'Compliance']
  },

  /* ---------------- BLOG POSTS ---------------- */

  'blog-phishing': {
    kicker: 'Blog — Threat Awareness',
    title: 'Security Training: Phishing Awareness',
    sub: 'April 2026',
    sections: [
      {
        p: ['A practical cybersecurity awareness write-up focused on recognizing phishing attempts, reducing risk, and improving everyday security behavior. As part of Mastercard\u2019s Cybersecurity Virtual Experience on Forage, I stepped into the role of a security analyst on the Security Awareness Team \u2014 analyzing suspicious emails and designing training to help teams spot them.']
      }
    ],
    tags: ['Phishing', 'Security Awareness', 'Forage'],
    links: [{ label: 'Read the full post', href: 'https://wp.nyu.edu/hemraj_patel/security-training-phishing-awareness/' }]
  },

  'blog-resilience': {
    kicker: 'Blog — Research',
    title: 'Implementing Operational Cyber Resilience in the IT Sector',
    sub: 'March 2026',
    sections: [
      {
        p: ['A short research paper exploring operational cyber resilience through the Operational Resilience Framework, with practical IT-sector security considerations. The IT sector sits at the foundation of nearly every industry \u2014 making its resilience a matter of national importance.']
      }
    ],
    tags: ['Cyber Resilience', 'Research Paper', 'Frameworks'],
    links: [{ label: 'Read the full paper', href: 'https://wp.nyu.edu/hemraj_patel/short-research-paper-implementing-operational-cyber-resilience-in-the-it-sector-using-the-operational-resilience-framework/' }]
  },

  'blog-athlete': {
    kicker: 'Blog — Personal Story',
    title: 'My Journey as an Athlete',
    sub: 'January 2025',
    sections: [
      {
        p: ['A personal story about discipline, resilience, and the competitive mindset shaped through swimming: from discovering the sport in 2008 and competing at state level by 2010, to 200+ state medals, national medals, and a final national medal in 2023 after returning from the COVID pause.']
      }
    ],
    tags: ['Athletics', 'Swimming', 'Discipline'],
    links: [{ label: 'Read the full story', href: 'https://wp.nyu.edu/hemraj_patel/my-journey-as-an-athlete/' }]
  },

  'blog-hello': {
    kicker: 'Blog — Introduction',
    title: 'Hello there!',
    sub: 'January 2025',
    sections: [
      {
        p: ['An introductory post offering a personal entry point into my background, interests, and professional direction \u2014 my journey from India to NYU, and from the pool to cybersecurity.']
      }
    ],
    tags: ['Introduction', 'Background'],
    links: [{ label: 'Read the full post', href: 'https://wp.nyu.edu/hemraj_patel/hello-world/' }]
  }
};
